### ISSUE TITLE
TZ query problem

### ISSUE THREAD

**Issue by jadeye** [dooglus/intersango#1]
# This is the log:

[03-Nov-2013 12:21:25 America/Chicago] PHP Fatal error:  Uncaught exception 'Error' with message 'Unknown or incorrect time zone: 'America/Chicago'' in /home/intersango/db.php:16
Stack trace:
#0 /home/public_html/intersango/db.php(72): do_query('set time_zone =...')
#1 /home/public_html/intersango/util.php(2): require_once('/home1/jadeye/p...')
#2 /home/public_html/btc-sango/index.php(11): require_once('/home1/jadeye/p...')
#3 {main}

  thrown in /home/public_html/intersango/db.php on line 16

I do not see where this query is suppose to go???
query: set time_zone = 'America/Chicago'

intersango/db.php(72): do_query('set time_zone =...')

A table? a text file???

HELP!

Thank you

**Comment by joeswhite** [comment]
I believe that your issue is arising from your database. Your database does not know America/Chicago is a timezone. 

This function is called on line 71 of db.php (https://github.com/dooglus/intersango/blob/master/db.php#L71)

I would suggest that if you are asking this question, (no offense, i do ask a lot of questions myself) that you consider all the work it takes to manage something this database/security intensive. Become familiar with your database/how it works, find where there security holes and flaws are in both your database and in the code you are working with. And make sure that you are doing everything with in the confines of the law. You may find that someone is easily able to hack your service via an exploitable flaw. You may find yourself with unwanted visitors at your door.

That being said, intersango is a pretty fun project to toy around with. But it is VERY old (over 2 years old) and it's most likely out of date. You should consider it as a reference, but you really should write your own for many many reasons... Now days everyone wants to see stats and wants a unique interface too. 

Please try to be as secure and safe with your project as you can be. I don't want to read about you getting hacked and losing any coins.

Anyway to continue,

To fix it you should simply need to log in to your server's command line and add timezone to your mysql server.

Since mysql is not always shipped with timezones, it is your responsibility to set them. To do this you must import them from your local linux operating system
Try to use the following command (assuming you are on UBUNTU, CentOS or Red Hat Enterprise)

mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql

that should allow you to get past this error and continue going forward.

good luck

**Comment by jadeye** [comment]
Thank you for your insights...
I have already fixed that!
But I do know you have a point!!!

Thank you
